### PR TITLE
Convert the awscli bash commands to Python

### PR DESCRIPTION
**Pull request by RyPeck**
Quick conversion from the awscli and bash commands to Python. This
enables future plans to automate the updates to this repository and to
run this in AWS Lambda.

Python outputs the same policy document json that the old process does.

### CODE REVIEW

**Comment by z0ph** [comment]
Hey, Thanks @RyPeck for your update. I've been working on an automated workload since few days, let me know what do you think. (cc @0xdabbad00 )
- https://github.com/z0ph/aws_managed_policies

As per my first tests, it's running pretty well.

**Comment by RyPeck** [comment]
Hey @z0ph - I'm working on the same thing, slightly different approach. I have it working all locally in a Python script (git commits too). Next is to get it scheduled in AWS Lambda.

**Comment by z0ph** [comment]
Wanted to do the same all serverless, but sounds difficult to run git commands using python.

Don't hesitate to ask some help if needed, or if I can work with you on this topic.

See you,

**Comment by RyPeck** [comment]
Closed in favor of #3

**Pull request closed without merging**
